# Generated by Django 4.0.4 on 2022-06-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_to_ics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='target_month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='upload',
            name='target_year',
            field=models.IntegerField(),
        ),
    ]
