# Generated by Django 4.0.4 on 2022-07-29 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_to_ics', '0002_alter_upload_target_month_alter_upload_target_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='excel',
            field=models.FileField(upload_to='excel_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx'], message='Ar keliamas failas yra ".xlsx"?')]),
        ),
    ]
